#!/usr/bin/env python3
import os, re, glob

POST_DIR = "src/content/post"
OUT = ".reasonix/exemplar_candidates.md"

BLOCKLIST = {
    "2026-01-05-blogpost-template-ideas",
    "2026-06-21-md-playground",
    "2026-07-10-draft-tools-and-experiments",
    "2026-07-23-reasonix-ai-writing-workflow",
}

FIRST_PERSON = re.compile(r"\bI\b|\bI'm\b|\bmy\b|\bI'd\b|\bI've\b")
QUESTION = re.compile(r"\?")

def short_sentence_count(text):
    sents = re.split(r'(?<=[.!?])\s+', text)
    return sum(1 for s in sents if 0 < len(s.split()) <= 12)

def strip_mdx(raw):
    raw = re.sub(r'^---\n.*?\n---\n', '', raw, flags=re.DOTALL)
    out, in_code, in_refs = [], False, False
    for line in raw.split('\n'):
        s = line.strip()
        if s.startswith('```'):
            in_code = not in_code; continue
        if in_code: continue
        if re.match(r'^#{1,6}\s*References\b', s) or s == 'References':
            in_refs = True
        if in_refs: continue
        if s.startswith('import '): continue
        if s.startswith('#'): continue
        if s.startswith('!['): continue
        if re.match(r'^(-{3,}|\*{3,})$', s): continue
        out.append(line)
    return '\n'.join(out)

def paragraphs(text):
    result = []
    for p in re.split(r'\n\s*\n', text):
        p = p.strip()
        if not p: continue
        p = re.sub(r'<[a-zA-Z][^>]*>', ' ', p)
        p = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', p)
        p = re.sub(r'\[\d+\]', '', p)
        p = re.sub(r'\s+', ' ', p).strip()
        if p: result.append(p)
    return result

def is_clean_prose(p):
    if '<' in p: return False
    for marker in ('class=', 'className', 'style=', '</', 'href='):
        if marker in p: return False
    letters = sum(c.isalpha() for c in p)
    if letters / max(len(p), 1) < 0.75: return False
    return True

def score(p):
    s = 0
    if FIRST_PERSON.search(p): s += 2
    if QUESTION.search(p): s += 2
    s += min(short_sentence_count(p), 4)
    words = len(p.split())
    if 25 <= words <= 90: s += 2
    elif words < 15: s -= 2
    if p.count('; ') >= 3: s -= 1
    return s

candidates = []
files = sorted(glob.glob(os.path.join(POST_DIR, "*.mdx")))
sampled_from = 0
for f in files:
    slug = os.path.basename(f).replace('.mdx', '')
    if slug in BLOCKLIST: continue
    with open(f, encoding='utf-8') as fh:
        raw = fh.read()
    fm = re.match(r'^---\n(.*?)\n---\n', raw, flags=re.DOTALL)
    if fm and re.search(r'draft:\s*true', fm.group(1)): continue
    sampled_from += 1
    for p in paragraphs(strip_mdx(raw)):
        if len(p.split()) < 12: continue
        if not is_clean_prose(p): continue
        sc = score(p)
        if sc >= 4:
            candidates.append((sc, slug, p))

candidates.sort(key=lambda x: -x[0])
selected, per_post = [], {}
for sc, slug, p in candidates:
    if per_post.get(slug, 0) >= 2: continue
    if any(p[:60] == q[:60] for _, _, q in selected): continue
    selected.append((sc, slug, p))
    per_post[slug] = per_post.get(slug, 0) + 1
    if len(selected) >= 15: break

lines = ["# Exemplar candidates (review before promoting)", ""]
lines.append("Generated by .reasonix/sample_voice.py. Auto-scored candidates")
lines.append("only. This file does NOT touch the curated Voice Exemplars in")
lines.append("STYLE_GUIDE.md. Read them. Manually promote any that genuinely")
lines.append("sound like the voice by pasting them into that section.")
lines.append("")
for sc, slug, p in selected:
    lines.append(f"## [score {sc}] from `{slug}`")
    lines.append("")
    lines.append(p)
    lines.append("")

with open(OUT, "w", encoding='utf-8') as fh:
    fh.write('\n'.join(lines).rstrip() + '\n')

print(f"Sampled {sampled_from} posts ({len(files)} files; drafts + blocklisted excluded).")
print(f"Wrote {len(selected)} clean candidates to {OUT} for review.")
for sc, slug, p in selected[:5]:
    print(f"  [score {sc}] {slug}: {p[:70]}...")
