/**
 * build-parts.mjs — turns sketchbook-ui components into static SVG for the deck.
 *
 *   cd presentations/etec534-ip2/sketch && npm install && npm run parts
 *
 * sketchbook-ui (https://github.com/SarthakRawat-1/sketchbook-ui, MIT) is a React
 * component library. A reveal.js deck is not a React app, and it does not need to
 * be one: the parts of the library this deck uses — the paper, notebook and
 * sticky-note cards, the hand-drawn dividers and the paper-grain filters — are
 * drawings, not behaviour. So they are rendered once, here, with React's static
 * renderer, and written out as an SVG sprite the slides can <use>.
 *
 * Output (both committed, so rendering the deck needs only Quarto):
 *   ../sketchbook-parts.include.html   hidden <svg> holding the filters and one <symbol>
 *                              per component; included after <body> by Quarto
 *   ../vendor/rough.js         Rough.js (MIT), which draws the diagram strokes
 */
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { Card, Divider, SketchProvider } from "sketchbook-ui";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const deck = join(here, "..");
const version = (name) =>
	JSON.parse(readFileSync(join(here, "node_modules", name, "package.json"), "utf8")).version;

/** The markup between a component's <svg ...> and </svg>. */
function innerSvg(markup) {
	const open = markup.indexOf("<svg");
	const start = markup.indexOf(">", open) + 1;
	const end = markup.lastIndexOf("</svg>");
	if (open < 0 || end < 0) throw new Error("component did not render an <svg>");
	return markup.slice(start, end);
}

// The shared filters and paper-grain patterns every component refers to by id.
const defs = innerSvg(renderToStaticMarkup(h(SketchProvider, null)));

const symbols = [];
const symbol = (id, viewBox, body) =>
	symbols.push(
		`<symbol id="${id}" viewBox="${viewBox}" preserveAspectRatio="none" overflow="visible">${body}</symbol>`,
	);

for (const variant of ["paper", "notebook", "sticky"]) {
	symbol(`sk-card-${variant}`, "0 0 600 500", innerSvg(renderToStaticMarkup(h(Card, { variant }, ""))));
}
for (const variant of ["scribble", "dashed", "zigzag"]) {
	symbol(
		`sk-divider-${variant}`,
		"0 0 600 40",
		innerSvg(renderToStaticMarkup(h(Divider, { variant, orientation: "horizontal" }))),
	);
}
symbol(
	"sk-divider-dashed-v",
	"0 0 40 600",
	innerSvg(renderToStaticMarkup(h(Divider, { variant: "dashed", orientation: "vertical" }))),
);

const sprite = `<!--
  GENERATED by sketch/build-parts.mjs — do not edit by hand.
  Cards, dividers and paper-grain filters are sketchbook-ui ${version("sketchbook-ui")} components
  (https://github.com/SarthakRawat-1/sketchbook-ui, MIT licence, © 2026 sketchbook-ui),
  rendered to static SVG with react-dom/server ${version("react-dom")}.
-->
<svg id="sketchbook-parts" width="0" height="0" aria-hidden="true" focusable="false"
     style="position:absolute;width:0;height:0;overflow:hidden;pointer-events:none">
${defs}
${symbols.join("\n")}
</svg>
`;
writeFileSync(join(deck, "sketchbook-parts.include.html"), sprite);

mkdirSync(join(deck, "vendor"), { recursive: true });
writeFileSync(
	join(deck, "vendor/rough.js"),
	`/*! Rough.js ${version("roughjs")} | https://roughjs.com | MIT License | Copyright (c) 2019 Preet Shihn */\n` +
		readFileSync(join(here, "node_modules/roughjs/bundled/rough.js"), "utf8"),
);

console.log(
	`sketchbook-parts.include.html  ${symbols.length} symbols, ${(sprite.length / 1024).toFixed(1)} KB` +
		`\nvendor/rough.js        roughjs ${version("roughjs")}`,
);
